spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: Mysql_1234
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.1.239:3306/knowledge?useUnicode=true&useSSL=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
          druid:
            initial-size: 5
            max-active: 500
            min-idle: 10
            max-wait: 3000
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
        slave:
          username: test_reader
          password: notw_test_@k2eDzdd14f
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.1.239:3306/knowledge?useUnicode=true&useSSL=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
          druid:
            initial-size: 5
            max-active: 500
            min-idle: 10
            max-wait: 3000
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
  pagehelper:
    helperDialect:mysql
    reasonable:true
    supportMethodsArguments:true
    params:count=countSql