spring:
  redis:
    host: 192.168.1.178
    port: 6379
    password: qkk2018
    timeout: 1000
    database: 1
    pool:
        time-between-eviction-runs: 10
        min-idle: 5
        max-active: 500
        max-idle: 50
        max-wait: 30000
        maxWaitMillis: 300
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: false
    #集群环境打开下面注释，单机不需要打开
    #cluster:
    #集群信息
    #nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    ##默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #maxRedirects: 3
    #哨兵模式打开
    #sentinel:
      #master: master1
      #nodes: 172.16.33.216:16001,172.16.33.216:16002
      
      
  

#  springboot  rocket配置
rocketmq:
  name-server: 192.168.1.241:9876
  producer:
    group: dianfeng_knowledge
    send-message-timeout: 300000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-next-server: true
    retry-times-when-send-async-failed: 0
    retry-times-when-send-failed: 2